### ISSUE TITLE
Whenever your not having your cursor over an object the box doesn't appear like it should in the normal Studio

### ISSUE THREAD

**Issue by xCoderJay** [Roblox/future-is-bright#122] opened 2018-09-01 16:09 UTC

**Comment by xCoderJay** [comment] 2018-09-01 16:11
I'll add some pictures dw

**Comment by donkeyrat** [comment] 2018-09-02 01:14
I believe the problem is the studio version is broken and the proper images are not working. This has been happening and the built in images on studio arent showing up.

**Comment by zeux** [comment] 2018-09-28 21:00
Cursors seem to work in v15, closing this.

**Closed by zeux** 2018-09-28 21:00 UTC
