### ISSUE TITLE
FIB crashes after trying to open Teamcreate place 

### ISSUE THREAD

**Issue by Ceiron** [Roblox/future-is-bright#137] opened 2018-10-07 15:24 UTC
FIB crashes after trying to open Teamcreate place. There is no problem with local or non teamcreate tho.
Also in earlier version it was crashing with teamcreate like per 5 min.  I was hoping it could get fixed in this version.

- requesting access then this
![unknown](https://user-images.githubusercontent.com/10236345/46583349-44836b00-ca5e-11e8-884a-069c999369aa.png)

**Comment by Kellerite** [comment] 2018-10-13 02:13
Having the same issue, for some reason, FiB versions are different from regular Roblox Studio versions, so that could be the cause of the issue. 
![Uploading image.png…]()

**Comment by zeux** [comment] 2018-12-13 19:08
Should be fixed in v16.

**Closed by zeux** 2018-12-13 19:08 UTC
