### ISSUE TITLE
DirectX 12 Compatibility

### ISSUE THREAD

**Issue by turtlesmelons** [Roblox/future-is-bright#45] opened 2017-07-26 13:59 UTC
How can I run it with DirectX 12? It says I need DirectX 11 when I launch the studio in the donwload. What can I do?

**Comment by drcanariez** [comment] 2017-07-26 15:20
I also have this problem. I really don't get it, if you have DirectX 12 you also have DirectX 11, but my Direct3D is 11.1

**Comment by zeux** [comment] 2017-07-26 16:10
This message indicates that your GPU doesn't support DirectX 11. You can check this by running dxdiag and looking at the Display tab - Direct3D DDI should be 11 or greater; in your case it's probably 10 or 10.1.

**Comment by drcanariez** [comment] 2017-07-26 16:13
![image](https://user-images.githubusercontent.com/30472956/28631615-d7e54b28-71fb-11e7-8d75-54162286b9c0.png)

**Comment by drcanariez** [comment] 2017-07-26 16:17
I understand now, I looked at my feature levels and it said 10_1

**Comment by zeux** [comment] 2017-07-26 16:18
Yeah, sorry, the right field to look at is Feature Levels.

**Comment by drcanariez** [comment] 2017-07-26 16:20
When support comes out for DirectX 10, I will be excited. It's worth the wait!

**Comment by zeux** [comment] 2017-07-26 16:22
Closing as duplicate of #38.

**Closed by zeux** 2017-07-26 16:22 UTC

**Comment by turtlesmelons** [comment] 2017-07-26 16:26
It says I have Direct 3D DII 11.1, DirectX 12, and Windows 10. That should
![image](https://user-images.githubusercontent.com/30464044/28632168-518a4366-7238-11e7-8b44-b57713186a4e.png)

**Comment by drcanariez** [comment] 2017-07-26 16:28
Read your Feature Levels. When you switch to Windows 10 it shows an incorrect DirectX.

**Comment by turtlesmelons** [comment] 2017-07-26 16:29
Oh, ok, I see. I guess I will have to wait, but thats fine.
