### ISSUE TITLE
I have directx 11 but is says I dont

### ISSUE THREAD

**Issue by spartanwb117** [Roblox/future-is-bright#87] opened 2017-12-17 20:38 UTC
I don't know what is wrong but I can't open it.

**Comment by tsbuilderboy** [comment] 2018-01-30 21:42
We don't have much to work with, buddy. Could we have a screenshot and some info on your PC?

**Comment by zeux** [comment] 2018-03-20 23:58
Your GPU most likely does not support DirectX 11; dxdiag doesn't make this super easy to see unfortunately. Closing as duplicate of #38.

**Closed by zeux** 2018-03-20 23:58 UTC
Labels: duplicate
