### ISSUE TITLE
Setting LightingMode to ShadowMap with GlobalShadows off crashes Roblox.

### ISSUE THREAD

**Issue by CloneTrooper1019** [Roblox/future-is-bright#43] opened 2017-07-25 23:44 UTC
I ran into this issue while I was trying to enable shadow maps in crossroads, since the place doesn't have GlobalShadows enabled.

**Comment by zeux** [comment] 2017-07-26 01:24
Duplicate of #8

**Closed by zeux** 2017-07-26 01:24 UTC
