### ISSUE TITLE
SurfaceLight issues

### ISSUE THREAD

**Issue by Sparkypen7** [Roblox/future-is-bright#25] opened 2017-07-23 15:25 UTC
Odd pixels appear around the border when I have a SurfaceLight in a part. When closer to the part, the pixels vanish, but they are visible from far away. 

![image](https://user-images.githubusercontent.com/11379504/28500614-5c5759ba-6f99-11e7-8ece-e978414e8705.png)

Enabling Shadows on the SurfaceLight removes these pixels.

But having shadows on enabled, I changed the light to face the bottom, and this is what happens: 

![image](https://user-images.githubusercontent.com/11379504/28500701-c9fd6562-6f9a-11e7-85fc-ed3a22c32808.png)

I put the glitched part next to a row of parts and this happens:
![image](https://user-images.githubusercontent.com/11379504/28500694-aac1e1e6-6f9a-11e7-8921-42c74b0eacb6.png)

**Comment by Sparkypen7** [comment] 2017-07-23 15:26
Also, Enabling Shadows removes these pixels.

**Comment by Sparkypen7** [comment] 2017-07-23 15:30
![image](https://user-images.githubusercontent.com/11379504/28500671-47b122ce-6f9a-11e7-9237-7f2fbb259500.png)
With shadows enabled, I changed the surface light to facing the bottom, it glitches out the part.

**Comment by zeux** [comment] 2017-07-23 16:53
Duplicate of #13

**Closed by zeux** 2017-07-23 16:53 UTC
