### ISSUE TITLE
ShadowMap buffer doesn't get cleared when GlobalShadows is set to false.

### ISSUE THREAD

**Issue by CloneTrooper1019** [Roblox/future-is-bright#44] opened 2017-07-25 23:49 UTC
If you turn off GlobalShadows while in ShadowMap mode, the most recently rendered shadow map stays in the buffer. It looks really weird when moving the camera around.

**Comment by Rytimiscurisin** [comment] 2017-07-26 00:52
That may be the same case as #36 . Can you send a gif of this?

**Comment by zeux** [comment] 2017-07-26 01:23
Duplicate of #36

**Closed by zeux** 2017-07-26 01:23 UTC
