### ISSUE TITLE
When trying to use "shadow map" Roblox studio crashes

### ISSUE THREAD

**Issue by od149** [Roblox/future-is-bright#26] opened 2017-07-23 19:21 UTC

**Comment by hunte922** [comment] 2017-07-23 19:43
Duplicate of #2. You need to turn on GlobalShadows before enabling ShadowMap.

**Comment by hunte922** [comment] 2017-07-23 23:12
You've posted this twice (#27). Can you close this one since it's less detailed?

**Comment by zeux** [comment] 2017-07-25 01:52
Fixed in v2, download it from https://github.com/Roblox/future-is-bright/releases

**Closed by zeux** 2017-07-25 01:52 UTC
