### ISSUE TITLE
DirectX Problems

### ISSUE THREAD

**Issue by RahadianNorman** [Roblox/future-is-bright#48] opened 2017-07-29 06:33 UTC
i have DirectX 12 but its not working for "future is bright" should i downgrade it ro DirectX 11 or 3D?

**Comment by zeux** [comment] 2017-07-29 18:14
Your GPU does not support DirectX 11 even though your OS does. Closing as duplicate of #38.

**Closed by zeux** 2017-07-29 18:14 UTC
