### ISSUE TITLE
Shadow map works on windows 10, but will not work on windows 7, ive tested both operating systems and i just cannot get it to work on windows 7

### ISSUE THREAD

**Issue by od149** [Roblox/future-is-bright#27] opened 2017-07-23 19:50 UTC

**Comment by hunte922** [comment] 2017-07-23 19:55
Duplicate of #2.

**Comment by zeux** [comment] 2017-07-25 01:52
Fixed in v2, you can get the new build from https://github.com/Roblox/future-is-bright/releases

**Closed by zeux** 2017-07-25 01:52 UTC
