### ISSUE TITLE
When will this be available for Mac/OS

### ISSUE THREAD

**Issue by Stxel** [Roblox/future-is-bright#82] opened 2017-11-18 23:56 UTC
I am wondering as I am a user of the following system, and you said one would be done like **months** ago.

**Comment by craftsmashbuild** [comment] 2017-12-02 05:12
~~hopefully never since mac is inferior to pc /s~~

So from what I know the goal is to develop a good lighting technology, the focus at the moment from what I know isn't performance or platform availability.

**Comment by zeux** [comment] 2017-12-06 22:20
This is a duplicate of #3 anyway, so closing this - please refer to #3 for macOS updates (which should happen momentarily...).

**Closed by zeux** 2017-12-06 22:20 UTC
Labels: duplicate
